version: '3'

services:
  wikit-neo4j:
    image: neo4j:4.4.4-community
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - ./data/neo4j:/data
  wikit-nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./containers/nginx/config:/etc/nginx/conf.d
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - wikit-neo4j
      - wikit-auth
      - wikit-data
      - wikit-rating
  wikit-auth:
    build:
      context: ./backend
      dockerfile: ../containers/auth.dockerfile
    volumes:
      - ./backend/dist:/wikit/dist
      - ./backend/config.yml:/wikit/config.yml
    depends_on:
      - wikit-neo4j
  wikit-data:
    build:
      context: ./backend
      dockerfile: ../containers/data.dockerfile
    volumes:
      - ./backend/dist:/wikit/dist
      - ./backend/config.yml:/wikit/config.yml
    depends_on:
      - wikit-neo4j
  wikit-rating:
    build:
      context: ./backend
      dockerfile: ../containers/rating.dockerfile
    volumes:
      - ./backend/dist:/wikit/dist
      - ./backend/config.yml:/wikit/config.yml
    depends_on:
      - wikit-neo4j
