version: '3'

services:
  wikit-nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./containers/nginx/config:/etc/nginx/conf.d
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - wikit-auth
  wikit-auth:
    build:
      context: ./backend
      dockerfile: ../containers/auth.dockerfile
    volumes:
      - ./backend/apps:/wikit/apps
      - ./backend/libs:/wikit/libs
      - ./backend/config.yml:/wikit/config.yml
      - ./backend/nest-cli.json:/wikit/nest-cli.json
      - ./backend/tsconfig.json:/wikit/tsconfig.json
      - ./backend/tsconfig.build.json:/wikit/tsconfig.build.json
