version: '3'

services:
  wikit-neo4j:
    image: neo4j:4.4.4-community
    volumes:
      - ./data/neo4j:/data
  wikit-nginx:
    build:
      context: ./
      dockerfile: ./containers/nginx/nginx.prod.dockerfile
    ports:
      - 80:80
    depends_on:
      - wikit-neo4j
      - wikit-auth
      - wikit-data
  wikit-auth:
    build:
      context: ./backend
      dockerfile: ../containers/auth.prod.dockerfile
    depends_on:
      - wikit-neo4j
  wikit-data:
    build:
      context: ./backend
      dockerfile: ../containers/data.prod.dockerfile
    depends_on:
      - wikit-neo4j
