version: '3'

services:
  wikit-neo4j:
    image: neo4j:4.4.4-community
    volumes:
      - ./data/neo4j:/data
  wikit-nginx:
    build:
      context: ./
      dockerfile: ./containers/nginx/nginx.prod.dockerfile
    ports:
      - 80:80
    depends_on:
      - wikit-auth
      - wikit-data
      - wikit-rating
      - wikit-search
      - wikit-image
  wikit-auth:
    build:
      context: ./backend
      dockerfile: ${PWD:-..}/containers/auth.prod.dockerfile
    depends_on:
      - wikit-neo4j
  wikit-data:
    build:
      context: ./backend
      dockerfile: ${PWD:-..}/containers/data.prod.dockerfile
    depends_on:
      - wikit-neo4j
  wikit-rating:
    build:
      context: ./backend
      dockerfile: ${PWD:-..}/containers/rating.prod.dockerfile
    depends_on:
      - wikit-neo4j
  wikit-search:
    build:
      context: ./backend
      dockerfile: ${PWD:-..}/containers/search.prod.dockerfile
    depends_on:
      - wikit-neo4j
  wikit-image:
    build:
      context: ./backend
      dockerfile: ${PWD:-..}/containers/image.prod.dockerfile
    volumes:
      - ./data/images:/wikit/images
